### ISSUE TITLE
"Apply" button in Drupal on commissions with openings

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/commissions#11]
Link to apply to the board/commission goes at the bottom of the sidebar component and only appears when the board/commission has vacancies or holdovers. The link to apply is displayed as a [blue button](https://patterns.boston.gov/components/detail/button--default.html).

Text above the button: "We have openings:"
Text inside the button: "Apply Online"

**Comment by fionawhim** [comment]
OK, I played around with a few different treatments:

![127 0 0 1_8888_board-and-commission 2](https://user-images.githubusercontent.com/260837/40502526-3cfe5ff4-5f59-11e8-95da-db3397d09b49.png)
![127 0 0 1_8888_board-and-commission 1](https://user-images.githubusercontent.com/260837/40502527-3d1263a0-5f59-11e8-919c-d692fb42f1c9.png)
![127 0 0 1_8888_board-and-commission](https://user-images.githubusercontent.com/260837/40502528-3d2273d0-5f59-11e8-850f-2202d8496a66.png)

**Comment by paylakatel** [comment]
These are great! I think the last one is the most straight forward. Thinking showing the number of opening/vacancies could be confusing/discourage people to apply if there are no "open" seats but there are holdovers. 

Looking at these I noticed a couple other things - could we: 
- also make "RESOURCES" in lower case italic Lora like the others? 
- left align the "Apply Online" button?
- change the label for "Seats" to "Total Seats"?

**Comment by fionawhim** [comment]
@paylakatel Looks like there may be a data issue w/ open seats. If we were showing a # of open seats, I’d want it to include holdovers as "open". I may have to calculate those "myself" rather than using the View_1.

I could change the "RESOURCES" style though I copied the format from public notices: https://www.boston.gov/public-notices/41821 I don't have a strong opinion on this consistency, could show it to Sebastian.
